### ISSUE TITLE
Possible default female model shown to other clients without customized skins

### ISSUE THREAD

**Issue by dagibbet** [QRCore-RedM-Re/qr-appearance#1]
Line 94 in Utils/functions.lua: (model load for all player peds)

Citizen.InvokeNative(0x77FF8D35EEC6BBC4, PlayerPedId(), 0, 0)

-- (solution - for female models)
 ped outfits (MetaPedOutfit struct) have fullOutfit flag, which basically reset player’s morph (but actually affects everything that somehow related to expressions system) on apply. But for whatever reason R* only do this against remote players.

So why mp_male works and mp_female is broken? Thing is default outfit (indexes as 0, used in “default outfit” native as well) for mp_female for whatever reason uses this flag, not allowing to properly sync expressions. What’s the solution? – Use outfit index that doesn’t have this flag enabled, for example 7.

-- _EQUIP_PED_OUTFIT_PRESET
Citizen.InvokeNative(0x77FF8D35EEC6BBC4, PlayerPedId(), 7, true)

Please note that randomly pasting this code won’t help, make sure you’re doing it every time after setting player model (mp_female) and you properly handle meta ped components (i.e. removing them before applying), so it won’t end up with mess.

Reference: https://forum.cfx.re/t/redm-devs-its-possible-your-female-models-are-broken-on-all-servers/1803615

(great work btw) - Dag

**Comment by mn9-29** [comment]
thx for help
